### ISSUE TITLE
tabs are cut by my cutting plotter

### ISSUE THREAD

**Issue by alpharesearch** [addam/Export-Paper-Model-from-Blender#18]
Hello,
I'm using a Silhouette SD cutting plotter with Robocut https://launchpad.net/robocut and Ubuntu 10.10...  I can export the SVG from Blender via your script (thank you!), everything works very good. 
The cutting plotter software cuts the path just fine, however the tabs are not connected with dashed lines so it cuts the lines off as well.
It would be nice if the script could generate different layers in the SVG file. Like a print layer with all the lines also on the tabs and a cut layer with dashed lines on the tabs. The cut layer could be disabled by default.
Regards,
Markus

**Comment by addam** [comment]
Now the script exports tabs with dashed/dash-dotted lines depending on the angle, so this should not be a problem anymore.
