### ISSUE TITLE
Notify the user about tilted quads

### ISSUE THREAD

**Issue by addam** [addam/Export-Paper-Model-from-Blender#2]
If there are quads in the model that are not flat, the user should be notified. They may wish to cancel the export process and edit their model beforehand.

**Comment by Treehee** [comment]
I usually just use triangulate on all my paper models, since it doesn't render flat edges anyways :)

**Comment by addam** [comment]
Oh, this issue is actually fixed, anyway. Thanks for bumping it up :)
