### ISSUE TITLE
Image in SVG file is out of paper

### ISSUE THREAD

**Issue by mond-cz** [addam/Export-Paper-Model-from-Blender#23]
When I open exported SVG file, image with UV map is placed totally out of paper, in a left upper corner of working place. It's a small thing . . .
(Tested in Illustrator CS5)

**Comment by comac2k** [comment]
I've done some tests using both inkscape and illustrator cs6 and three different versions of the script:
* stable: the version available at blender.org repository (https://git.blender.org/gitweb/gitweb.cgi/blender-addons-contrib.git/blob/6dcaf5f5b25bd16e45052abd2b90940f6c587b4f:/io_export_paper_model.py)
* prepull: the last version before my pull request was merged (https://github.com/addam/Export-Paper-Model-from-Blender/tree/3e2aa644adb2028e9a7a7692c95386ccea41d59c)
* postpull: current head at github.com (https://github.com/addam/Export-Paper-Model-from-Blender/tree/0b36cd266a622ee4b4c86b4cfefe9df1a4adc239)

Both "stable" and "prepull" throw errors when trying to export in "single linked" mode (I'm using blender 2.76). After fixing them, they would generate a tiny background image invisible both in inkscape and illustrator. The inkscape screenshots show this image selected in the XML editor. Its size is 0.287 x 0.2 milimeters.

"Postpull" version runs without errors and generates an SVG file that opens and displays properly both in inkscape and illustrator.

In short: I don't know what happened before, but right now, on current blender versions, the script version on github master seems to be working just fine for both inkscape and illustrator.

#### Inkscape "stable": ![inkscape_stable](https://cloud.githubusercontent.com/assets/12332784/12495594/e0e143d0-c090-11e5-9a48-6c95f7c9f055.png)
#### Inkscape "prepull": ![inkscape_prepull](https://cloud.githubusercontent.com/assets/12332784/12495601/ef953558-c090-11e5-90b6-de64187d5052.png)
#### Inkscape "postpull": ![inkscape_postpull](https://cloud.githubusercontent.com/assets/12332784/12495608/f591c4e4-c090-11e5-8ab5-02e7f769131f.png)

#### Illustrator "stable": ![illustrator_stable](https://cloud.githubusercontent.com/assets/12332784/12495610/fc874008-c090-11e5-9a6d-317473f23fd7.png)
#### Illustrator "prepull": ![illustrator_prepull](https://cloud.githubusercontent.com/assets/12332784/12495613/01532e1c-c091-11e5-9166-e8fb29cc6a59.png)
#### Illustrator "postpull": ![illustrator_postpull](https://cloud.githubusercontent.com/assets/12332784/12495614/0632b7e0-c091-11e5-8232-4c3a3ca605d9.png)

**Comment by addam** [comment]
Wow, great! Comac2k, I owe you a lolcat of awesomenezz for dealing with this issue.
