### ISSUE TITLE
Blender wiki page still talks about "Make Unfoldable" operator

### ISSUE THREAD

**Issue by jdugge** [addam/Export-Paper-Model-from-Blender#33]
The "Make Unfoldable" operator was renamed "Unfold" in d24a1ae1d8e6cec01cb19dc0d293be9085e3fab3, but the [Blender wiki page for the script](http://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Import-Export/Paper_Model) still refers to "Make Unfoldable".

**Comment by addam** [comment]
Fixed. Thanks for the bugreport.

**Comment by jdugge** [comment]
Thank *you* for the great add-on!
