### ISSUE TITLE
TypeError: normal() takes exactly 4 arguments (1 given) when exporting or unfolding

### ISSUE THREAD

**Issue by julienbalas** [addam/Export-Paper-Model-from-Blender#53]
Hi
I'm a total noob in Blender and python-in-blender so may be I've missed a very simple step.

I've installed the addon (git clone, Ctrl-Alt-U, choose python file, activate the plugin)
On the starting scene with the cube when i do File->Export->Paper Model i get an 
"TypeError: normal() takes exactly 4 arguments (1 given) " on line 783

The line 783 is         self.normal = M.geometry.normal(v.co for v in self.verts)

In the Blender-python console if i try
import mathutils as M
cubedata = bpy.data["Cube"]
for v in cubedata.vertices:
  print(M.geometry.normal(v.co))
i get the same message

Blender 2.72 on Debian 8

Best regards.

**Comment by julienbalas** [comment]
If I revert to the e0fdfc0436f6b4ff65bb2e9c97a2fabfc6700e9a way of calculating the normal, it's working !
I get a pdf file

**Comment by addam** [comment]
The other option for you is to download a newer version of Blender.
I thought that 2.70+ is okay, but obviously I was wrong. I will update that info and then I'll close this bug report.

**Comment by addam** [comment]
The update was made on 2014-12-30, so blender 2.73 is needed, actually. Fixed, closing.
