### ISSUE TITLE
Normal() takes 4 arguments (1 given) 

### ISSUE THREAD

**Issue by wvlia5** [addam/Export-Paper-Model-from-Blender#56]
I have never used this addon. When I try to export, it says
```
line 799, in __init__
    self.normal = M.geometry.normal(v.co for v in self.vertices)
TypeError: normal() takes exactly 4 arguments (1 given) 
```
I have checked that the generator used as an argument, generates 3 Vector

I haven't marked seams or anything. I admit I don't know how to use it, but assumptions should be checked and error messages with usage hints should be printed

**Comment by wvlia5** [comment]
I tried it again and it magically worked... I don't know why, because I didn't change anything

**Comment by addam** [comment]
This error happens if you use blender 2.73 or earlier.

**Comment by wvlia5** [comment]
Thanks. Impressive software
