### ISSUE TITLE
Some artifacts on folds

### ISSUE THREAD

**Issue by yarigk** [addam/Export-Paper-Model-from-Blender#61]
Hello.
I have artifacts on folds of image.
Maybe I'm doing something wrong (?)
![shot](https://user-images.githubusercontent.com/10969859/42039590-2fd89758-7b07-11e8-9fa3-36135d4fec62.PNG)

**Comment by yarigk** [comment]
Thank you for such a quick reaction. Pleasantly surprised.
I use Cycles Render engine. Render does not have such artifacts (screenshot below).
![shot2](https://user-images.githubusercontent.com/10969859/42040591-70ad9e52-7b09-11e8-97d9-f2f88bdc1963.PNG)
Material - defuse, texture on material in png format.
I can attach my model, if it necessary.

**Comment by addam** [comment]
Can you please send the model to my mail adominec@gmail.com? I'm afraid I'll not be able to fix this error, but I'd like to find out what's going on.

**Comment by addam** [comment]
Sorry, I was not able to neither reproduce nor fix this error. Closing.
