### ISSUE TITLE
Support for Blender 2.8

### ISSUE THREAD

**Issue by wout** [addam/Export-Paper-Model-from-Blender#62]
Hi Adam,
First of all, thank you for this fantastic plug-in.
It's the best unfolding software I've used to date.

I was wondering if you are planning support for Blender 2.8.
I suppose the API has changed slightly.

![image](https://user-images.githubusercontent.com/107324/46664254-bd023d00-cbc0-11e8-983a-be0f62c0b2a2.png)

Thanks!

**Comment by wout** [comment]
Thanks, i'll have a look at it. It's no longer included by default, right?

**Comment by addam** [comment]
It is, and will be in 2.80 release.
I just didn't finish the port, so these changes are not commited yet.

**Comment by wout** [comment]
Great, thanks!

**Comment by gaianinja** [comment]
I also await this functionality eagerly! Thanks for your hard work! :)
