### ISSUE TITLE
line styles don't work anymore for concave/convex lines

### ISSUE THREAD

**Issue by jdreske** [addam/Export-Paper-Model-from-Blender#63]
I just updated to v1.0 (Blender 2.79) and it seems the line styles doesn't work anymore. 
No matter what I set - all inner folding lines are solid (not dotted ) and convex
(but I can change the colour)

By the way- great work!

**Comment by addam** [comment]
fixed in blender28 branch

**Comment by jdreske** [comment]
line styles work again in blender28, 
but concave/convex lines are mixed up.
This simple model should only have 1 concave line:

![2step blend](https://user-images.githubusercontent.com/22870457/59156705-ff598200-8a9f-11e9-956e-8c88cd47ec4d.png)

[2step.blend.zip](https://github.com/addam/Export-Paper-Model-from-Blender/files/3269353/2step.blend.zip)

**Comment by addam** [comment]
You're right, it's all screwed up. I'll fix it.

**Comment by addam** [comment]
fixed again in `blender28`.
