### ISSUE TITLE
Limited Island Size get too big 

### ISSUE THREAD

**Issue by jdreske** [addam/Export-Paper-Model-from-Blender#64]
If I limit the island size to A3 and unfold a default cube size 0.1x0.1x0.1 / scale 1:1 I get one island with 6 faces. If I try to print it on A3 the addon reports an error.
OK, there might be some margins, tabs and text in the way- so I increase the pagesize of the exporter.
If have to increase the width to 0.45, the height is not important (>0.39 is ok) to export.
(the resulting diagonal island is ~0.36x0.36cm.)

This was just one example, but I have often problems to find the right size settings.
I have a more complex model right now and I have to decrease the Page size of the Limit Island Size option down to 0.26 x 0.37 to be able to print it as A3 .pdf.
(The smallest real margin on the right side in the output is 3.7cm. The exporter says roughly 1.0x)

Why does it need some much empty space?

**Comment by addam** [comment]
I believe this has been fixed by commit 1fce1b5 "fix island rotation". The scenario you describe works correctly.

I'm closing this issue. If anybody encounters issues with Limit Island Size, please provide the example.

**Comment by jdreske** [comment]
Sorry for this question, but where is the "limit island size" checkbox and menu located in blender 2.8? I only found the "paper model islands" under "object data" tab.
