### ISSUE TITLE
Exporting using python console 

### ISSUE THREAD

**Issue by MahmoudAshraf-CIS** [addam/Export-Paper-Model-from-Blender#65]
am trying to export the default cube as a paper model but I got the following error 
`
AttributeError: 'ExportPaperModel' object has no attribute 'object'
`
and here is a screenshot of blender
![image](https://user-images.githubusercontent.com/20478561/52611126-a3ce0d80-2e8c-11e9-8be0-070f27061841.png)

steps :- first openup blender and go to the python console then ran the following lines in order 
```
import bpy
bpy.data.objects['Cube'].select = True # Select the default Blender Cube
bpy.ops.object.mode_set(mode='OBJECT')
bpy.ops.object.editmode_toggle()
bpy.ops.export_mesh.paper_model(filepath='D:\\')
```

windows 10 - 64bit - blender version 2.79

sorry if it's a naive problem but am new at both blender and python, so any pointers would be great 
thanks in advance

**Comment by addam** [comment]
You are right, the script cannot be used from console. I have it on my task list for blender 2.80.

**Comment by addam** [comment]
Fixed in branch blender28
