### ISSUE TITLE
SVG export fails

### ISSUE THREAD

**Issue by jdreske** [addam/Export-Paper-Model-from-Blender#67]
Exporting to SVG does not work:

<img width="739" alt="epmfb_svg_b" src="https://user-images.githubusercontent.com/22870457/55435946-48222580-559b-11e9-90e3-3e2d3422f2bf.png">

However exporting to PDF works.

Export-Paper-Model-from-Blender v1.0, Blender 2.79, OSX

**Comment by addam** [comment]
this is probably fixed in `blender28` branch. If not, please provide an example model that fails.
