### ISSUE TITLE
Error trying exporting simple textured mesh

### ISSUE THREAD

**Issue by beitz** [addam/Export-Paper-Model-from-Blender#71]
The error occurs when tryting to click on "File/Export/Paper Model" in blender 2.8 rc2. 
I attached a screenshot and the blend file used. 

[error.zip](https://github.com/addam/Export-Paper-Model-from-Blender/files/3421725/error.zip)

**Comment by addam** [comment]
This error has been fixed. Please try the current version: https://raw.githubusercontent.com/addam/Export-Paper-Model-from-Blender/master/io_export_paper_model.py

**Comment by beitz** [comment]
Thanks for the quick response! This has fixed the problem. 
Sorry for not getting the newest version. Kind of thought the newest blender would automatically include the newest addons.

**Comment by addam** [comment]
Thanks for testing.

It makes sense that blender rc2 should work. I was just waiting for somebody to test this fixed version. I'll update it now so that the script is okay in final release.
