### ISSUE TITLE
Color export error Blender 2.83

### ISSUE THREAD

**Issue by xiantuan** [addam/Export-Paper-Model-from-Blender#83]
![image](https://user-images.githubusercontent.com/10727426/83887966-c23fd280-a77b-11ea-9d7f-f057e8dd22e4.png)

![image](https://user-images.githubusercontent.com/10727426/83888106-f87d5200-a77b-11ea-9768-ee56e3c2ff06.png)

Error:
textures: Form Materials
Scale:1/20 or 1/15
other material 

Right:
textures: Form Materials
Scale:1/6 

Blender 2.83

**Comment by xiantuan** [comment]
PDF 4A

**Comment by addam** [comment]
So... the blue and the white material did export correctly, and the yellow one failed?

**Comment by xiantuan** [comment]
yellow becomes blue.  *.SVG right

**Comment by addam** [comment]
I could not reproduce the error.
