### ISSUE TITLE
Addon not working.

### ISSUE THREAD

**Issue by HatWearingMann** [addam/Export-Paper-Model-from-Blender#92]
I cannot find it in the add-ons tab and attempting to install it from here also doesn't work (v2.93.4).

**Comment by addam** [comment]
I just tested the addon in fresh Blender 2.93.4 installation on Windows and Linux, and I cannot confirm this bug. Everything appears OK to me.
* Please make sure that no filtering is applied to the addon list ("Enabled Add-ons only" must be unchecked, and the category switched to "All" or "Import-Export").
* Look into the system console and if there are any suspicious messages, please post a screenshot.

**Comment by HatWearingMann** [comment]
Those error messages after enabling the add-on.
[image: obraz.png]
[image: obraz.png]



sob., 18 wrz 2021 o 16:57 Addam Dominec ***@***.***>
napisał(a):

**Comment by addam** [comment]
Sorry, apparently it is not possible to attach images when posting through e-mail. Please, add the screenshots directly on github.com.

**Comment by HatWearingMann** [comment]
You just have to click the text to expand the email's contents. If that
don't work I'll send it later as now I am in school.

wt., 21 wrz 2021, 07:57 użytkownik Addam Dominec ***@***.***>
napisał:

**Comment by HatWearingMann** [comment]
![obraz](https://user-images.githubusercontent.com/79970290/134394041-977b926e-72b0-439f-8f24-67cb5c1cb2ea.png)
![obraz](https://user-images.githubusercontent.com/79970290/134394050-ee15bb5a-1045-49bc-b28f-9e9363e8e3a5.png)

**Comment by addam** [comment]
Thank you, it should be fixed now. Please try downloading and installing the add-on again.

This issue is, however, not related to the default copy of the script that is built in into Blender. I believe the script also works correctly when _not_ installed from here.
