### ISSUE TITLE
Missing texture after Export with the textures option activated

### ISSUE THREAD

**Issue by sanchezlucas** [addam/Export-Paper-Model-from-Blender#97]
Reported also on blender.org

**System Information**
Operating system: Windows-10-10.0.22621-SP0 64 Bits
Graphics card: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 527.56

**Blender Version**
Broken: version: 3.5.0, branch: blender-v3.5-release, commit date: 2023-03-29 02:56, hash: `1be25cfff18b`
Worked: 3.2.2

**Addon Information**
Name: Export Paper Model (1, 2)
Author: Addam Dominec

**Short description of error**
The export comes without the baked textures after activating the respective options, also  related on the forums https://blenderartists.org/t/export-paper-model/476597/485.

The dev build hosted on github has the same issue

**Exact steps for others to reproduce the error**
Open the export dialog > On the 'Textures' dropdown choose  'full render' or 'from material' > Export Paper Model

----

Result with this dev build:

![image](https://user-images.githubusercontent.com/13504335/229324397-afaaeb62-0aa3-4c8e-8b19-b66dceb51c94.png)

Desired result with 3.2.2

![image](https://user-images.githubusercontent.com/13504335/229324481-dbd6e207-cd6b-4afa-9f55-a0d0f1b5e288.png)

**Comment by HatWearingMann** [comment]
Same issue here.;

**Comment by HatWearingMann** [comment]
It doesn't work for me either, I'm using a image texture material for my model.

**Comment by hystricidae** [comment]
It's the same for me. Problems with the export of textures seemed to occure quite frequently in the past, though.

**Comment by addam** [comment]
Fixed in a8a71ae, please test.
Remaining part is that the textured export crashes if the mesh has no material. Solution will be to automatically create (and delete) a dummy material.
