### ISSUE TITLE
Dodecahedron not unfolding with correct ratios.

### ISSUE THREAD

**Issue by wakass** [addam/Export-Paper-Model-from-Blender#99]
Hi there,

I'm running into some issues unfolding a dodecahedron-like shape, specifically when the sides are not all 'equal', so to say. I've illustrated it in the attached screenshot.

The faces are all planar, but it looks like the interior angles and lengths of the edges of the ngons are not preserved. Was hoping there is an easy solution to this, or if i'm doing something silly.

Regards,

WakA

<img width="1604" alt="Screenshot 2023-06-11 at 08 59 24" src="https://github.com/addam/Export-Paper-Model-from-Blender/assets/8496465/9437d7ef-da15-434d-9cdc-7775b299c581">

**Comment by addam** [comment]
Can you please send me the blend file? It seems quite improbable that the script would produce incorrect shapes but if true, it would be a serious bug.

**Comment by wakass** [comment]
Please find attached the blend file.  It does seem a bit odd, but i'm finding comparable results using the regular UV unwrap (which i think paper model might rely on?) Correct unwrapping seems to happen only when using unwrap 'project  from view' with the viewport is aligned to the face normal. 

[dodecahedron_unfold_test.blend.zip](https://github.com/addam/Export-Paper-Model-from-Blender/files/11714941/dodecahedron_unfold_test.blend.zip)

**Comment by addam** [comment]
As far as I can tell, the angles and length are all correct. If you enable the `Display Stretch` overlay, it shows nothing noticeable:
![image](https://github.com/addam/Export-Paper-Model-from-Blender/assets/278643/bc2441d9-a029-446d-94c4-51d0eff93aa9)

I would close this assuming the skewed polygon is just an optical illusion. Do you have any measurement to assure there is an actual distortion?

**Comment by addam** [comment]
Also, overlaying the screenshot from 3D View with the screenshot of UV editor shows that they are exactly the same shape:
![image](https://github.com/addam/Export-Paper-Model-from-Blender/assets/278643/a05cb192-1066-46a3-b4ef-c63c99fc8977)

**Comment by wakass** [comment]
You are completely correct.. this is definitely an optical "illusion". Thanks for looking into this and elucidating the issue!

Regards
